version: '3.7'

services:
  objloader2dev:
    image: objloader2dev
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - 8085:80
    volumes:
      - ./src:/project/src:ro
      - ./resource:/project/resource:ro
      - ./test:/project/test:ro
    command: ["nginx", "-g", "daemon off;"]
    container_name: objloader2dev
